from __future__ import annotations

import json
from pathlib import Path

import typer

from control_mapper.batch import export_results, map_batch, map_collector_findings
from control_mapper.engine import list_finding_types, map_finding

app = typer.Typer(help="Map technical security findings to supporting control references.")


@app.command("list-findings")
def list_findings() -> None:
    for finding_type in list_finding_types():
        typer.echo(finding_type)


@app.command("map")
def map_command(
    finding_type: str = typer.Argument(..., help="Normalized finding type."),
    json_output: bool = typer.Option(False, "--json", help="Emit machine-readable JSON."),
) -> None:
    try:
        result = map_finding(finding_type)
    except KeyError as exc:
        typer.echo(str(exc), err=True)
        raise typer.Exit(code=2) from exc

    if json_output:
        typer.echo(json.dumps(result.model_dump(mode="json"), indent=2))
        return

    typer.echo(f"{result.finding_type}: {result.title}")
    typer.echo(f"Mapping version: {result.mapping_version}")
    typer.echo("Evidence needed:")
    for item in result.evidence_needed:
        typer.echo(f"- {item}")
    typer.echo("References:")
    for reference in result.references:
        typer.echo(
            f"- {reference.framework} {reference.reference}: {reference.title} — {reference.relevance}"
        )
    typer.echo(result.disclaimer)


@app.command("map-file")
def map_file(
    input_path: Path = typer.Argument(..., exists=True, dir_okay=False, readable=True),
    output: Path | None = typer.Option(None, "--output", "-o"),
) -> None:
    """Map normalized finding types or check IDs from CSV/JSON."""
    try:
        results = map_batch(input_path)
        if output is not None:
            export_results(results, output)
    except (KeyError, ValueError) as exc:
        typer.echo(f"Mapping failed: {exc}", err=True)
        raise typer.Exit(code=2) from exc

    for result in results:
        typer.echo(f"{result.finding_type}: {len(result.references)} references")
    if output is not None:
        typer.echo(f"Exported: {output}")


@app.command("map-collector")
def map_collector(
    findings_path: Path = typer.Argument(..., exists=True, dir_okay=False, readable=True),
    output: Path | None = typer.Option(None, "--output", "-o"),
) -> None:
    """Map findings.json generated by security-evidence-collector."""
    try:
        results = map_collector_findings(findings_path)
        if output is not None:
            export_results(results, output)
    except ValueError as exc:
        typer.echo(f"Collector mapping failed: {exc}", err=True)
        raise typer.Exit(code=2) from exc

    typer.echo(f"Mapped {len(results)} collector findings")
    for result in results:
        typer.echo(
            f"{result.source_finding_id or '-'} | {result.source_check_id or '-'} | "
            f"{result.finding_type} | {len(result.references)} references"
        )
    if output is not None:
        typer.echo(f"Exported: {output}")


if __name__ == "__main__":
    app()
